### ISSUE TITLE
Transformer chaos containment

### ISSUE THREAD

**Issue by texasmichelle** [tensorflow/swift-models#436]
Before more transformer-based language models are added to this repo, let's pay down some debt on the ones we have:

- [ ] #432 Disentangle CoLA and BERT
- [ ] #433 Verify BERT variants (ALBERT and RoBERTA are untested)
- [ ] #434 GPT-2 and BERT alignment

This will make additional models easier to add and maintain.
